version: '3.5'

services:
    hcs-backend:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: nodemon --legacy-watch --delay 10 start
        ports:
            - "${HCS_BACK_PORT}:${BACK_PORT}"
        depends_on:
            - db
        volumes:
            - ../src/back:/usr/src/app
        environment:
            NODE_ENV: ${NODE_ENV}
            HOST: ${BACK_HOST}
            PORT: ${BACK_PORT}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
    hcs-frontend:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: nodemon --legacy-watch --delay 10 start
        ports:
            - "${HCS_FRONT_PORT}:3000"
        depends_on:
            - hcs-backend
        volumes:
            - ../src/front:/usr/src/app
        environment:
            NODE_ENV: ${NODE_ENV}
            REACT_APP_DOCKER_HOST: ${DOCKER_HOST}
            REACT_APP_HCS_BACK_PORT: ${HCS_BACK_PORT}
    db:
        restart: always
        privileged: true
        image: mongo:4.0
        volumes:
            - data-volume:/data/db
        ports:
            - "${DB_PORT}:${DB_PORT}"
volumes:
    data-volume: