version: '3.5'

services:
    hcs-backend:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: nodemon --legacy-watch --delay 10 start
        ports:
            - "${HCS_BACK_PORT}:${BACK_PORT}"
        depends_on:
            - db
        volumes:
            - ../src/back:/usr/src/app
        environment:
            NODE_ENV: ${NODE_ENV}
            HOST: ${BACK_HOST}
            PORT: ${BACK_PORT}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_PORT: ${DB_PORT}
            API_TOKEN: ${API_TOKEN}
    hcs-frontend:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
#        command: nodemon --legacy-watch --delay 10 start
        ports:
            - "${HCS_FRONT_PORT}:3000"
        depends_on:
            - hcs-backend
        volumes:
            - ../src/front:/usr/src/app
        environment:
            NODE_ENV: ${NODE_ENV}
            API_HOST: ${API_HOST}
            API_TOKEN: ${API_TOKEN}
    db:
        restart: 'no'
        image: mongo:4.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ${DB_HOST_VOLUME_PATH}:/data/db